"""baseline

Revision ID: 8453cb52458a
Revises: 
Create Date: 2026-07-03 22:50:40.553410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8453cb52458a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_columns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.Column('column_id', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Text(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('nullable', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='asset'
    )
    op.create_table('asset_relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rel_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('from_table', sa.Text(), nullable=True),
    sa.Column('from_columns', sa.Text(), nullable=True),
    sa.Column('to_table', sa.Text(), nullable=True),
    sa.Column('to_columns', sa.Text(), nullable=True),
    sa.Column('join_condition', sa.Text(), nullable=True),
    sa.Column('cardinality', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('validation_level', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('validation_metrics', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('validation_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='asset'
    )
    op.create_table('asset_tables',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('row_count_stats', sa.Text(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('grain', sa.Text(), nullable=True),
    sa.Column('pk', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='asset'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_tables', schema='asset')
    op.drop_table('asset_relations', schema='asset')
    op.drop_table('asset_columns', schema='asset')
    # ### end Alembic commands ###
