<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { copyRecipeVersion, createRecipe, generateRecipeSql, listRecipes, submitRecipe } from "@/api/recipes";
const rows = ref<any[]>([]); const loading = ref(false);
const dialogVisible = ref(false); const form = ref({ recipe_id: "", recipe_name: "", description: "", domain: "" });
async function load() { loading.value = true; try { const res = await listRecipes({ page: 1, page_size: 100 }); rows.value = res.data?.items || []; } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "加载配方失败"); } finally { loading.value = false; } }
async function saveDraft() { if (!form.value.recipe_id.trim()) { ElMessage.warning("请输入配方编码"); return; } try { await createRecipe({ ...form.value, primary_tables: [], joins: [] }); ElMessage.success("草稿已创建"); dialogVisible.value = false; await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "创建失败"); } }
async function copyVersion(row: any) { try { await copyRecipeVersion(row.recipe_id, row.version); ElMessage.success("已复制新版本"); await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "复制失败"); } }
async function submit(row: any) { try { await submitRecipe(row.recipe_id, row.version); ElMessage.success("已提交审核"); await load(); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "提交失败"); } }
async function previewSql(row: any) { try { const res = await generateRecipeSql(row.recipe_id, row.version); await ElMessageBox.alert(res.data.sql, "SQL 预览（仅生成，不执行）", { confirmButtonText: "关闭" }); } catch (e: any) { ElMessage.error(e?.response?.data?.detail || "SQL 生成失败"); } }
onMounted(load);
</script>
<template><div class="p-4"><RePageHeader title="关系配方库" subtitle="版本化管理、审核发布和只读 SQL 预览。"><template #actions><el-button type="primary" @click="dialogVisible = true">新建草稿</el-button></template></RePageHeader><el-card v-loading="loading" class="mt-4"><el-table :data="rows"><el-table-column prop="recipe_id" label="配方"/><el-table-column prop="version" label="版本" width="80"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="domain" label="业务域"/><el-table-column prop="description" label="说明" show-overflow-tooltip/><el-table-column label="操作" width="280"><template #default="{ row }"><el-button size="small" text @click="copyVersion(row)">复制版本</el-button><el-button v-if="row.status === 'draft'" size="small" text type="primary" @click="submit(row)">提交审核</el-button><el-button size="small" text type="success" @click="previewSql(row)">SQL预览</el-button></template></el-table-column></el-table><el-empty v-if="!rows.length" description="暂无配方"/></el-card><el-dialog v-model="dialogVisible" title="新建配方草稿" width="520px"><el-form :model="form" label-width="90px"><el-form-item label="配方编码" required><el-input v-model="form.recipe_id" /></el-form-item><el-form-item label="配方名称"><el-input v-model="form.recipe_name" /></el-form-item><el-form-item label="业务域"><el-input v-model="form.domain" /></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" @click="saveDraft">创建草稿</el-button></template></el-dialog></div></template>
